#!/bin/bash
# Install (or remove) the weekly launchd job for THIS checkout.
#
# The plist is generated here rather than committed, because launchd needs
# absolute paths and those are different on every machine. Nothing about the
# schedule is baked into the repository.
#
#   ./scripts/install_schedule.sh                 # Sunday 22:00 by default
#   ./scripts/install_schedule.sh --day 6 --hour 23 --minute 30
#   ./scripts/install_schedule.sh --run           # trigger one run right now
#   ./scripts/install_schedule.sh --uninstall
#
# --day uses launchd's numbering: 0 = Sunday ... 6 = Saturday.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LABEL="${PAPERS_LAUNCHD_LABEL:-com.academicpapergrabber.weekly}"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

DAY=0
HOUR=22
MINUTE=0
ACTION=install

while [ $# -gt 0 ]; do
  case "$1" in
    --day) DAY="$2"; shift 2 ;;
    --hour) HOUR="$2"; shift 2 ;;
    --minute) MINUTE="$2"; shift 2 ;;
    --uninstall) ACTION=uninstall; shift ;;
    --run) ACTION=run; shift ;;
    -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

if [ "$(uname -s)" != "Darwin" ]; then
  cat >&2 <<EOF
This installer is macOS-only (launchd). On Linux, run the same entry point from
cron or a systemd timer instead:

  0 22 * * 0  $ROOT/scripts/run_weekly.sh

EOF
  exit 1
fi

case "$ACTION" in
  uninstall)
    launchctl unload -w "$PLIST" 2>/dev/null || true
    rm -f "$PLIST"
    echo "removed $LABEL"
    exit 0
    ;;
  run)
    launchctl kickstart -k "gui/$(id -u)/$LABEL" 2>/dev/null \
      || launchctl start "$LABEL" 2>/dev/null \
      || { echo "job not loaded; running directly" && exec "$ROOT/scripts/run_weekly.sh"; }
    echo "triggered $LABEL - follow it with: tail -f $ROOT/logs/\$(date +%F).log"
    exit 0
    ;;
esac

mkdir -p "$HOME/Library/LaunchAgents" "$ROOT/logs"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/install_schedule.sh for $ROOT - do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$ROOT/scripts/run_weekly.sh</string>
    </array>

    <!-- launchd tracks the system timezone, so this stays at the wall-clock
         time across DST changes, unlike a fixed-UTC cron entry. -->
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key>
        <integer>$DAY</integer>
        <key>Hour</key>
        <integer>$HOUR</integer>
        <key>Minute</key>
        <integer>$MINUTE</integer>
    </dict>

    <key>WorkingDirectory</key>
    <string>$ROOT</string>

    <key>StandardOutPath</key>
    <string>$ROOT/logs/launchd.out.log</string>
    <key>StandardErrorPath</key>
    <string>$ROOT/logs/launchd.err.log</string>

    <key>RunAtLoad</key>
    <false/>

    <!-- A run takes 10-20 minutes: arXiv wants 3s between requests, then six
         subagents write the chapters. Do not let launchd call it hung. -->
    <key>ExitTimeOut</key>
    <integer>3600</integer>

    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
EOF

plutil -lint "$PLIST" > /dev/null
launchctl unload -w "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"

DAYS=(周日 周一 周二 周三 周四 周五 周六)
printf 'installed %s\n  schedule : %s %02d:%02d (local time)\n  repo     : %s\n  plist    : %s\n' \
  "$LABEL" "${DAYS[$DAY]}" "$HOUR" "$MINUTE" "$ROOT" "$PLIST"
echo "  trigger  : $0 --run"
